using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WeenieViewer.Enums;

namespace VGI_Item_Viewer.Enum
{
    public enum EquipmentSet
    {
        Invalid = 0,
        Test = 1,
        Test2 = 2,
        Unknown3 = 3,
        CarraidasBenediction = 4,
        NobleRelic = 5,
        AncientRelic = 6,
        AlduressaRelic = 7,
        Ninja = 8,
        EmpyreanRings = 9,
        ArmMindHeart = 10,
        ArmorPerfectLight = 11,
        ArmorPerfectLight2 = 12,
        Soldiers = 13,
        Adepts = 14,
        Archers = 15,
        Defenders = 16,
        Tinkers = 17,
        Crafters = 18,
        Hearty = 19,
        Dexterous = 20,
        Wise = 21,
        Swift = 22,
        Hardened = 23,
        Reinforced = 24,
        Interlocking = 25,
        Flameproof = 26,
        Acidproof = 27,
        Coldproof = 28,
        Lightningproof = 29,
        SocietyArmor = 30,
        ColosseumClothing = 31,
        GraveyardClothing = 32,
        OlthoiClothing = 33,
        NoobieArmor = 34,
        AetheriaDefense = 35,
        AetheriaDestruction = 36,
        AetheriaFury = 37,
        AetheriaGrowth = 38,
        AetheriaVigor = 39,
        RareDamageResistance = 40,
        RareDamageBoost = 41,
        OlthoiArmorDRed = 42,
        OlthoiArmorCRat = 43,
        OlthoiArmorCRed = 44,
        OlthoiArmorDRat = 45,
        AlduressaRelicUpgrade = 46,
        AncientRelicUpgrade = 47,
        NobleRelicUpgrade = 48,
        CloakAlchemy = 49,
        CloakArcaneLore = 50,
        CloakArmorTinkering = 51,
        CloakAssessPerson = 52,
        CloakLightWeapons = 53,
        CloakMissileWeapons = 54,
        CloakCooking = 55,
        CloakCreatureEnchantment = 56,
        CloakCrossbow = 57,
        CloakFinesseWeapons = 58,
        CloakDeception = 59,
        CloakFletching = 60,
        CloakHealing = 61,
        CloakItemEnchantment = 62,
        CloakItemTinkering = 63,
        CloakLeadership = 64,
        CloakLifeMagic = 65,
        CloakLoyalty = 66,
        CloakMace = 67,
        CloakMagicDefense = 68,
        CloakMagicItemTinkering = 69,
        CloakManaConversion = 70,
        CloakMeleeDefense = 71,
        CloakMissileDefense = 72,
        CloakSalvaging = 73,
        CloakSpear = 74,
        CloakStaff = 75,
        CloakHeavyWeapons = 76,
        CloakThrownWeapon = 77,
        CloakTwoHandedCombat = 78,
        CloakUnarmedCombat = 79,
        CloakVoidMagic = 80,
        CloakWarMagic = 81,
        CloakWeaponTinkering = 82,
        CloakAssessCreature = 83,
        CloakDirtyFighting = 84,
        CloakDualWield = 85,
        CloakRecklessness = 86,
        CloakShield = 87,
        CloakSneakAttack = 88,
        // Shou-Jen Shozoku Set
        Ninja_New = 89,
        CloakSummoning = 90,
        ShroudedSoul = 91,
        DarkenedMind = 92,
        CloudedSpirit = 93,
        MinorStingingShroudedSoul = 94,
        MinorSparkingShroudedSoul = 95,
        MinorSmolderingShroudedSoul = 96,
        MinorShiveringShroudedSoul = 97,
        MinorStingingDarkenedMind = 98,
        MinorSparkingDarkenedMind = 99,
        MinorSmolderingDarkenedMind = 100,
        MinorShiveringDarkenedMind = 101,
        MinorStingingCloudedSpirit = 102,
        MinorSparkingCloudedSpirit = 103,
        MinorSmolderingCloudedSpirit = 104,
        MinorShiveringCloudedSpirit = 105,
        MajorStingingShroudedSoul = 106,
        MajorSparkingShroudedSoul = 107,
        MajorSmolderingShroudedSoul = 108,
        MajorShiveringShroudedSoul = 109,
        MajorStingingDarkenedMind = 110,
        MajorSparkingDarkenedMind = 111,
        MajorSmolderingDarkenedMind = 112,
        MajorShiveringDarkenedMind = 113,
        MajorStingingCloudedSpirit = 114,
        MajorSparkingCloudedSpirit = 115,
        MajorSmolderingCloudedSpirit = 116,
        MajorShiveringCloudedSpirit = 117,
        BlackfireStingingShroudedSoul = 118,
        BlackfireSparkingShroudedSoul = 119,
        BlackfireSmolderingShroudedSoul = 120,
        BlackfireShiveringShroudedSoul = 121,
        BlackfireStingingDarkenedMind = 122,
        BlackfireSparkingDarkenedMind = 123,
        BlackfireSmolderingDarkenedMind = 124,
        BlackfireShiveringDarkenedMind = 125,
        BlackfireStingingCloudedSpirit = 126,
        BlackfireSparkingCloudedSpirit = 127,
        BlackfireSmolderingCloudedSpirit = 128,
        BlackfireShiveringCloudedSpirit = 129,
        ShimmeringShadowsSet = 130,
        BrownSocietyLocket = 131,
        YellowSocietyLocket = 132,
        RedSocietyBand = 133,
        GreenSocietyBand = 134,
        PurpleSocietyBand = 135,
        BlueSocietyBand = 136,
        GauntletGarb = 137,
        ParagonMissile = 138,
        ParagonCaster = 139,
        ParagonMelee = 140,
    }

    public static class EquipmentSetExtensions
    {
        public static string GetName(this EquipmentSet equipmentSet)
        {
            string setName = "";
            switch ((int)equipmentSet)
            {
                //case 1: setName = "SpellSetID_EnchantmentVersion"; break;
                //case 2: setName = "Test_EquipmentSet"; break;
                case 4: setName = "Carraida's Benediction"; break;
                case 5: setName = "Noble Relic"; break;
                case 6: setName = "Ancient Relic"; break;
                case 7: setName = "Relic Alduressa"; break;
                case 8: setName = "Shou-jen"; break;
                case 9: setName = "Empyrean Rings"; break;
                case 10: setName = "Arm, Mind, Heart"; break;
                case 11: setName = "Coat of the Perfect Light"; break;
                case 12: setName = "Leggings of Perfect Light"; break;
                case 13: setName = "Soldier's"; break;
                case 14: setName = "Adept's"; break;
                case 15: setName = "Archer's"; break;
                case 16: setName = "Defender's"; break;
                case 17: setName = "Tinker's"; break;
                case 18: setName = "Crafter's"; break;
                case 19: setName = "Hearty"; break;
                case 20: setName = "Dexterous"; break;
                case 21: setName = "Wise"; break;
                case 22: setName = "Swift"; break;
                case 23: setName = "Hardenend"; break;
                case 24: setName = "Reinforced"; break;
                case 25: setName = "Interlocking"; break;
                case 26: setName = "Flame Proof"; break;
                case 27: setName = "Acid Proof"; break;
                case 28: setName = "Cold Proof"; break;
                case 29: setName = "Lightning Proof"; break;
                case 30: setName = "Dedication"; break;
                case 31: setName = "Gladiatorial Clothing"; break;
                case 32: setName = "Ceremonial Clothing"; break;
                case 33: setName = "Protective Clothing"; break;
                //case 34: setName = "NoobieArmor_EquipmentSet"; break;
                case 35: setName = "Sigil of Defense"; break;
                case 36: setName = "Sigil of Destruction"; break;
                case 37: setName = "Sigil of Fury"; break;
                case 38: setName = "Sigil of Growth"; break;
                case 39: setName = "Sigil of Vigor"; break;
                case 40: setName = "Heroic Protector"; break;
                case 41: setName = "Heroic Destroyer"; break;
                //case 42: setName = "OlthoiArmorDRed_Set"; break;
                //case 43: setName = "OlthoiArmorCRat_Set"; break;
                //case 44: setName = "OlthoiArmorCRed_Set"; break;
                //case 45: setName = "OlthoiArmorDRat_Set"; break;
                //case 46: setName = "AlduressaRelicUpgrade_EquipmentSet"; break;
                //case 47: setName = "Upgraded Ancient Relic"; break;
                //case 48: setName = "NobleRelicUpgrade_EquipmentSet"; break;
                case 49: setName = "Weave of Alchemy"; break;
                case 50: setName = "Weave of Arcane Lore"; break;
                case 51: setName = "Weave of Armor Tinkering"; break;
                case 52: setName = "Weave of Assess Person"; break;
                case 53: setName = "Weave of Light Weapons"; break;
                case 54: setName = "Weave of Missile Weapons"; break;
                case 55: setName = "Weave of Cooking"; break;
                case 56: setName = "Weave of Creature Enchantment"; break;
                case 57: setName = "Weave of Missile Weapons"; break;
                case 58: setName = "Weave of Finesse"; break;
                case 59: setName = "Weave of Deception"; break;
                case 60: setName = "Weave of Fletching"; break;
                case 61: setName = "Weave of Healing"; break;
                case 62: setName = "Weave of Item Enchantment"; break;
                case 63: setName = "Weave of Item Tinkering"; break;
                case 64: setName = "Weave of Leadership"; break;
                case 65: setName = "Weave of Life Magic"; break;
                case 66: setName = "Weave of Loyalty"; break;
                case 67: setName = "Weave of Light Weapons"; break;
                case 68: setName = "Weave of Magic Defense"; break;
                case 69: setName = "Weave of Magic Item Tinkering"; break;
                case 70: setName = "Weave of Mana Conversion"; break;
                case 71: setName = "Weave of Melee Defense"; break;
                case 72: setName = "Weave of Missile Defense"; break;
                case 73: setName = "Weave of Salvaging"; break;
                case 74: setName = "Weave of Light Weapons"; break;
                case 75: setName = "Weave of Light Weapons"; break;
                case 76: setName = "Weave of Heavy Weapons"; break;
                case 77: setName = "Weave of Missile Weapons"; break;
                case 78: setName = "Weave of Two Handed Combat"; break;
                case 79: setName = "Weave of Light Weapons"; break;
                case 80: setName = "Weave of Void Magic"; break;
                case 81: setName = "Weave of War Magic"; break;
                case 82: setName = "Weave of Weapon Tinkering"; break;
                case 83: setName = "Weave of Assess Creature "; break;
                case 84: setName = "Weave of Dirty Fighting"; break;
                case 85: setName = "Weave of Dual Wield"; break;
                case 86: setName = "Weave of Recklessness"; break;
                case 87: setName = "Weave of Shield"; break;
                case 88: setName = "Weave of Sneak Attack"; break;
                case 89: setName = "Shou-Jen Shozoku"; break;
                case 90: setName = "Weave of Summoning"; break;
                case 91: setName = "Shrouded Soul"; break;
                case 92: setName = "Darkened Mind"; break;
                case 93: setName = "Clouded Spirit"; break;
                case 94: setName = "Minor Stinging Shrouded Soul"; break;
                case 95: setName = "Minor Sparking Shrouded Soul"; break;
                case 96: setName = "Minor Smoldering Shrouded Soul"; break;
                case 97: setName = "Minor Shivering Shrouded Soul"; break;
                case 98: setName = "Minor Stinging Darkened Mind"; break;
                case 99: setName = "Minor Sparking Darkened Mind"; break;
                case 100: setName = "Minor Smoldering Darkened Mind"; break;
                case 101: setName = "Minor Shivering Darkened Mind"; break;
                case 102: setName = "Minor Stinging Clouded Spirit"; break;
                case 103: setName = "Minor Sparking Clouded Spirit"; break;
                case 104: setName = "Minor Smoldering Clouded Spirit"; break;
                case 105: setName = "Minor Shivering Clouded Spirit"; break;
                case 106: setName = "Major Stinging Shrouded Soul"; break;
                case 107: setName = "Major Sparking Shrouded Soul"; break;
                case 108: setName = "Major Smoldering Shrouded Soul"; break;
                case 109: setName = "Major Shivering Shrouded Soul"; break;
                case 110: setName = "Major Stinging Darkened Mind"; break;
                case 111: setName = "Major Sparking Darkened Mind"; break;
                case 112: setName = "Major Smoldering Darkened Mind"; break;
                case 113: setName = "Major Shivering Darkened Mind"; break;
                case 114: setName = "Major Stinging Clouded Spirit"; break;
                case 115: setName = "Major Sparking Clouded Spirit"; break;
                case 116: setName = "Major Smoldering Clouded Spirit"; break;
                case 117: setName = "Major Shivering Clouded Spirit"; break;
                case 118: setName = "Blackfire Stinging Shrouded Soul"; break;
                case 119: setName = "Blackfire Sparking Shrouded Soul"; break;
                case 120: setName = "Blackfire Smoldering Shrouded Soul"; break;
                case 121: setName = "Blackfire Shivering Shrouded Soul"; break;
                case 122: setName = "Blackfire Stinging Darkened Mind"; break;
                case 123: setName = "Blackfire Sparking Darkened Mind"; break;
                case 124: setName = "Blackfire Smoldering Darkened Mind"; break;
                case 125: setName = "Blackfire Shivering Darkened Mind"; break;
                case 126: setName = "Blackfire Stinging Clouded Spirit"; break;
                case 127: setName = "Blackfire Sparking Clouded Spirit"; break;
                case 128: setName = "Blackfire Smoldering Clouded Spirit"; break;
                case 129: setName = "Blackfire Shivering Clouded Spirit"; break;
                case 130: setName = "Shimmering Shadows"; break;
            }

            return setName;
        }
    }
}
